//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLog
    {
        public long Id { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> Logtime { get; set; }
        public Nullable<System.DateTime> LogtimeEnd { get; set; }
        public string MenuId { get; set; }
        public string Fullname { get; set; }
    }
}
