//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ManageUsersEntities : DbContext
    {
        public ManageUsersEntities()
            : base("name=ManageUsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountLog> AccountLogs { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<MenuItemFunction> MenuItemFunctions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int MenuItemRoles_DeleteByRoleID(Nullable<int> iDRole)
        {
            var iDRoleParameter = iDRole.HasValue ?
                new ObjectParameter("IDRole", iDRole) :
                new ObjectParameter("IDRole", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MenuItemRoles_DeleteByRoleID", iDRoleParameter);
        }
    
        public virtual int MenuItemRoles_InsertItem(string menuItem_ID, Nullable<int> role_ID)
        {
            var menuItem_IDParameter = menuItem_ID != null ?
                new ObjectParameter("MenuItem_ID", menuItem_ID) :
                new ObjectParameter("MenuItem_ID", typeof(string));
    
            var role_IDParameter = role_ID.HasValue ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MenuItemRoles_InsertItem", menuItem_IDParameter, role_IDParameter);
        }
    }
}
