//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Collections.Generic;
[Serializable ]
    public partial class Role
    {
        public Role()
        {
            this.Groups = new HashSet<Group>();
            this.MenuItemFunctions = new HashSet<MenuItemFunction>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<MenuItemFunction> MenuItemFunctions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
